# Generated by Django 4.1.7 on 2024-06-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('hot', 'Hot'), ('cold', 'Cold'), ('bomb', 'Bomb'), ('vom', 'VOM')], default='hot', max_length=4)),
            ],
        ),
    ]
